# Generated by Django 5.0.6 on 2024-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('secondEmail', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Secondary email')),
                ('first_name', models.CharField(max_length=50, verbose_name='Fisrt name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('tel', models.CharField(max_length=9, null=True, unique=True, verbose_name='Phone number')),
                ('country', models.CharField(max_length=20, null=True, verbose_name='Country')),
                ('region', models.CharField(max_length=20, null=True, verbose_name='Region')),
                ('zipCode', models.IntegerField(null=True, verbose_name='Zip code')),
                ('username', models.CharField(max_length=10, null=True, verbose_name='User name')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='user/profileImages')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'get_latest_by': 'date_joined',
            },
        ),
    ]
