# Generated by Django 5.0.6 on 2024-06-01 22:35

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ASIN')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='price')),
                ('availability_status', models.BooleanField(default=True, verbose_name='avaible')),
                ('number_of_product_avaible', models.PositiveIntegerField(verbose_name='Number of product avaible')),
                ('image_link', models.CharField(max_length=255, verbose_name='Image link')),
                ('product_category', models.PositiveIntegerField(verbose_name='Category')),
                ('average_rating', models.FloatField(validators=[products.models.positive_validators], verbose_name='Average rating')),
                ('total_reviews', models.PositiveIntegerField(verbose_name='Total reviews')),
            ],
        ),
        migrations.AlterModelOptions(
            name='panier',
            options={'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='asin',
            field=models.CharField(max_length=100, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.commande', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='lignepanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.panier', verbose_name='Panier'),
        ),
        migrations.AlterField(
            model_name='lignepanier',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='lignepanier',
            name='asin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='ASIN'),
        ),
    ]
