# Generated by Django 5.0.6 on 2024-06-01 22:54

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_alter_panier_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[products.models.positive_validators], verbose_name='price'),
        ),
    ]
