# Generated by Django 5.0.6 on 2024-06-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='Manufacturer'),
        ),
    ]
